const GET_RECIPE= "GET RECIPE";
const GET_RECIPE_BY_NAME= "GET RECIPE BY NAME";
const GET_RECIPE_BY_ID= "GET RECIPE BY ID"
const GET_TYPE= "GET DETAIL";
const NAME_ASC= "NAME ASC";
const NAME_DESC= "NAME DESC";
const SCORE_MAX_TO_MIN="SCORE MAX TO MIN";
const SCORE_MIN_TO_MAX=" SCORE MIN TO MAX"
const POST_RECIPE = "POST_RECIPE"
const RESET = "Reset"


module.exports={
    GET_RECIPE,
    GET_RECIPE_BY_NAME,
    GET_RECIPE_BY_ID,
    GET_TYPE,
    NAME_ASC,
    NAME_DESC,
    SCORE_MAX_TO_MIN,
    SCORE_MIN_TO_MAX,
    POST_RECIPE,
    RESET
}
